import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/navbar";

import "../app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mida AI App",
  description: "Generated by MIDA AI app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar />

        <main>{children}</main>
  
      </body>
    </html>
  );
}
